[providers]
python = {}

[phases.setup]
nixPkgs = ['...', 'pango', 'harfbuzz', 'glib', 'fontconfig']
aptPkgs = [
    "libgobject-2.0-0",
    "libpango-1.0-0",
    "libharfbuzz0b",
    "libpangoft2-1.0-0",
    "libpangocairo-1.0-0",
    "libgdk-pixbuf2.0-0",
    "libglib2.0-0",
    "shared-mime-info"
]